input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["Result"]
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "result_index"
  }
}